### ISSUE TITLE
fastai2_to_opencv: benchmark issues

### ISSUE THREAD

**Issue by YashasSamaga** [cudawarped/fastai-notebooks#1]
1. OpenCV DNN does not support changing backends. You have to create a new `Net` object (even `net.clear()` won't help). More information [here](https://github.com/opencv/opencv/issues/14965).

2. OpenCV DNN performs lazy initialization. The first forward pass generally takes a lot of time (often in the order of hundreds of milliseconds to as much as seconds). Hence, the initialization time has a considerable impact on the benchmarks. The standard deviation of around 1.6ms is very high for a mean of 5.5ms. I suspect the initialization is having a considerable impact on the benchmark timings.

**Comment by cudawarped** [comment]
@YashasSamaga Thanks for your comments. 

>     1. OpenCV DNN does not support changing backends. You have to create a new `Net` object (even `net.clear()` won't help). More information [here](https://github.com/opencv/opencv/issues/14965).
I did not know this, I have forced the network to be initialized for each backend.  Would you expect to see a difference with the `DNN_TARGET_OPENCL_FP16` target? Is this limited by the version of OpenCL Nvidia supports?

>     2\. OpenCV DNN performs lazy initialization. The first forward pass generally takes a lot of time (often in the order of hundreds of milliseconds to as much as seconds). Hence, the initialization time has a considerable impact on the benchmarks. The standard deviation of around 1.6ms is very high for a mean of 5.5ms. I suspect the initialization is having a considerable impact on the benchmark timings.

The benchmark code was just to check that the inference timings were in the right ballpark.  That said I have made the adjustments you suggested.

**Comment by YashasSamaga** [comment]
>  Would you expect to see a difference with the DNN_TARGET_OPENCL_FP16 target? Is this limited by the version of OpenCL Nvidia supports?

I don't have much idea about the OpenCL backend. It doesn't use streams and often makes use of CPU fallbacks which dominates the performance. It certainly doesn't make use of tensor cores. Any gains would mostly be from reduced memory bandwidth usage and any losses would mostly be from fp16/fp32 conversions that take place when fallbacks are used.

**Comment by cudawarped** [comment]
@YashasSamaga Did you notice a significant speedup when processing batches of images?  I notice the documentation is for single image classification only.
In python ms/image goes from ~5 for a single image down to ~2.5 for a batch of 4 images.  Is this inline with your experience?

**Comment by YashasSamaga** [comment]
@cudawarped Yes, that's expected. You can observe a similar trend in the benchmarks posted [here](https://gist.github.com/YashasSamaga/a84cf2826ab2dc755005321fe17cd15d).
